# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }} 
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js (change node version to 18 for stability)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'  # השתמש בגרסה 18, שהיא יציבה יותר

      # Install dependencies
      - run: npm ci

      # Install Firebase dependencies explicitly if needed
      - run: npm install

      # Run tests
      - run: npm test
